[package]
name = "solana-stable-layout"
description = "Solana types with stable memory layouts. Internal use only."
documentation = "https://docs.rs/solana-stable-layout"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
default = ["abi-stable"]
abi-stable = ["dep:abi_stable"]

[dependencies]
solana-instruction = { workspace = true, default-features = false, features = [
    "std",
] }
solana-pubkey = { workspace = true, default-features = false }

abi_stable = { workspace = true, optional = true }

[dev-dependencies]
memoffset = { workspace = true }
